{{- if .Values.enableDns01 }}
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  access-token: {{ .Values.digitaloceanToken | quote }}
{{- end }}
